### ISSUE TITLE
image embedding error 

### ISSUE THREAD

**Issue by Npiechaud** [biigle/magic-sam#8]
Hey guys, 

Just reporting an error with the tool

I have had an error with magic-SAM that says "Could not load the image embedding" each time I press the SAM button. 
The processing seem to work normally (I mean, I see the little stars coming out of the hat) but i get the error when it stops. 
Other types of annotations are fine. I tried with Chrome and Edge. I also tried on different volumes in different projects. 
At least one other user I know has the same error. 

<img width="818" alt="Capture" src="https://github.com/biigle/magic-sam/assets/25684932/bb04d1c8-4694-4e4e-bdd9-0faa69a13a55">

This tool is very handy, hope it is an easy fix. 
Cheers

**Comment by dlangenk** [comment]
Hey Nils,

this has likely to do with #7. I did a quick fix for that image only. I will fix the issue behind that later. If you have another image that does not work. Just send me a mail and I'll quickly upload the fixed embedding. (Please note that we have a downtime of Maia and Sam from 2 to 9 today).

Best
Daniel

**Comment by Npiechaud** [comment]
Hi Daniel, 
Thanks for the quick response. I can wait for the general fix, no worries. 
What is a rotation flag? Is that set by the user? Something we can fix on our side?

cheers

**Comment by Npiechaud** [comment]
Ok, thanks for the info. We will plan accordingly. 

Cheers

**Comment by dlangenk** [comment]
@mzur Unfortunately this seems to be a different error (look at server log).

**Comment by mzur** [comment]
To clarify: BIIGLE's default behavior is to ignore the EXIF rotation flag (because we often have cameras facing down which randomly produce either rotation value of the flag). In this case BIIGLE mistakenly *does not* ignore this flag.

@dlangenk Can you please tell me which log entry you mean? Either you can paste it here or give me a timestamp.

**Comment by dlangenk** [comment]
It's the problem we talked about this morning.
For example this one:
```
array:7 [▼ // resources/views/admin/logs/index-redis.blade.php
  "message" => """
    Error while executing python command '/var/www/vendor/biigle/magic-sam/src/config/../resources/scripts/compute_embedding.py '/var/www/storage/magic_sam/sam_chec ▶
    Traceback (most recent call last):
      File "/var/www/vendor/biigle/magic-sam/src/config/../resources/scripts/compute_embedding.py", line 19, in <module>
        sam.to(device=device)
      File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 989, in to
        return self._apply(convert)
      File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
        module._apply(fn)
      File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
        module._apply(fn)
      File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
        module._apply(fn)
      File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
        param_applied = fn(param)
      File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 987, in convert
        return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
      File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
        torch._C._cuda_init()
    RuntimeError: No CUDA GPUs are available
    """
  "context" => array:1 [▶]
  "level" => 400
  "level_name" => "ERROR"
  "channel" => "production"
  "datetime" => "2023-07-27T10:52:02.028950+02:00"
  "extra" => []
]
```

**Comment by mzur** [comment]
I see. We fixed this issue temporarily and Magic SAM should work again. The long-term fix is in progress (i.e. switching to Docker Swarm with a GPU health check). I'll close this for now but please feel free to reopen if there are still issues.
